name: dutstore
description: Ecommerce App

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0
  get: ^4.0.0-nullsafety.2
  rxdart: ^0.26.0
  flutter_secure_storage: ^4.1.0
  connectivity: ^3.0.3
  shared_preferences: ^2.0.5
  dio: ^4.0.0
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.0.0
  smooth_page_indicator: ^0.3.0-nullsafety.0
  google_maps_flutter: ^2.0.6
  flutter_polyline_points: ^1.0.0
  flutter_slidable: ^0.6.0
  hive: ^2.0.4
  tuple: ^2.0.0
  geolocator: ^7.1.0
  geocoding: ^2.0.0
  flutter_local_notifications: 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/slide/
    - assets/images/branch/
    - assets/icons/

  fonts:
    - family: MuliBold
      fonts:
        - asset: assets/fonts/muli/Muli-Bold.ttf
    - family: MuliItalic
      fonts:
        - asset: assets/fonts/muli/Muli-BoldItalic.ttf
    - family: MuliExtraLight
      fonts:
        - asset: assets/fonts/muli/Muli-ExtraLight.ttf
    - family: MuliExtraLightItalic
      fonts:
        - asset: assets/fonts/muli/Muli-ExtraLightItalic.ttf
    - family: MuliItalic
      fonts:
        - asset: assets/fonts/muli/Muli-Italic.ttf
    - family: MuliLight
      fonts:
        - asset: assets/fonts/muli/Muli-Light.ttf
    - family: MuliLightItalic
      fonts:
        - asset: assets/fonts/muli/Muli-LightItalic.ttf
    - family: MuliRegular
      fonts:
        - asset: assets/fonts/muli/Muli-Regular.ttf
    - family: MuliSemiBold
      fonts:
        - asset: assets/fonts/muli/Muli-SemiBold.ttf
    - family: MuliSemiBoldItalic
      fonts:
        - asset: assets/fonts/muli/Muli-Semi-BoldItalic.ttf
