const Map<String, String> JP = {
  //login
  'description_logo': '無料投稿-必要に応じて検索',
  'user_email_phone_field': 'ユーザー名、電話番号、または電子メール',
  "password_field": 'パスワード',
  "login": 'ログイン',
  "forgot_password": 'パスワードをお忘れですか',
  "go_register": 'アカウントを持っていないのですか？ 登録',
  'or_sign_in_with': 'またはログイン',
  //register
  'username_field': 'ユーザー名',
  'name_field': 'フルネーム',
  'email_field': 'Eメール',
  'phone_field': '電話',
  'repassword_field': 'パスワードを認証する',
  'register': '登録',
  'go_login': 'すでにアカウントをお持ちですか？ ログイン',
  //forgot pass
  //more
  'account_balance': '勘定残高',
  'normal': '正常',
  'admin': '管理者',
  'update_info': '情報を編集する',
  'change_password': 'パスワードを変更する',
  'version': 'バージョン',
  'my_store': '私の店',
  'manage_posting': '投稿を管理する',
  'store_management': '店舗管理',
  'safe_purchase': '安全な購入',
  'help': '助けて',
  'about_tizi': 'Tiziについて',
  'appearance': '外観',
  'language': '言語',
  'log_out': 'ログアウト',
  'sign_in/sign_up': 'ログインサインアップ',
  //setting
  'setting': '設定',
  //common
  'home': 'ホームホーム',
  'saved_news': '保存されたニュース',
  'message': 'メッセージ',
  'more': 'もっと',
  'error': 'エラー',
  'skip': 'スキップ',
  'back': 'バック',
  'vn_language': 'ベトナム語',
  'jp_language': "日本語",
  'light_theme': "明るい背景",
  'dark_theme': "暗い背景",
  'settings': "設定",
  'select_language': "言語の選択",
  'input_code': "コードを入力します",
};
