const Map<String, String> VN = {
  //login
  'description_logo': 'Đăng tin miễn phí - Tìm tin như ý',
  'user_email_phone_field': 'Tên đăng nhập, SĐT hoặc email',
  "password_field": 'Mật khẩu',
  "login": 'Đăng nhập',
  "forgot_password": 'Quên mật khẩu',
  "go_register": 'Bạn chưa có tài khoản? Đăng ký',
  'or_sign_in_with': 'Hoặc đăng nhập',
  //register
  'username_field': 'Tên đăng nhập',
  'name_field': 'Hồ Ngọc Dũng',
  'email_field': 'Email',
  'phone_field': 'Số điện thoại',
  'repassword_field': 'Nhập lại',
  'register': 'Đăng ký',
  'go_login': 'Bạn đã có tài khoản? Đăng nhập',
  //forgot pass
  //more
  'account_balance': 'Số dư',
  'normal': 'Thường',
  'admin': 'Admin',
  'update_info': 'Cậo nhật thông tin',
  'change_password': 'Đổi mật khẩu',
  'version': 'Phiên bản',
  'my_store': 'Gian hàng của bạn',
  'manage_posting': 'Quản lý tin đăng',
  'store_management': 'Quản lý gian hàng',
  'safe_purchase': 'An toàn khi mua',
  'help': 'Trợ giúp',
  'about_tizi': 'Về Tizi',
  'appearance': "Giao diện",
  'language': 'Ngôn ngữ',
  'log_out': 'Đăng xuất',
  'sign_in/sign_up': 'Đăng nhập/ Đăng ký',
  //setting
  'setting': 'Cài đặt',
  //common
  'home': 'Trang chủ',
  'saved_news': 'Tin lưu',
  'message': 'Tin nhắn',
  'more': 'Thêm',
  'error': 'Lỗi',
  'skip': 'Bỏ qua',
  'back': 'Quay lại',
  'vn_language': 'Tiếng Việt',
  'jp_language': "Tiếng Nhật",
  'light_theme': "Nền sáng",
  'dark_theme': "Nền tối",
  'settings': "Cài đặt",
  'select_language': "Lựa chọn ngôn ngữ",
  'input_code': "Nhập mã code",
  'hint_search_text': "Bạn cần tìm gì ?",
  'history_search': "Lịch sử tìm kiếm",
  'result_search': "Kết quả tìm kiếm",
  'negotiate': "Thỏa thuận",
  'detail_product': "Chi tiết sản phẩm",
  'view_more': "Xem thêm",
  'see_less': "Thu gọn",
  'view_shop': "Xem trang",
  'report': "Báo xấu",
  'personal': "Cá nhân",
  'num_of_news': "Số tin đăng",
  'create_at': "Ngày tham gia",
  'recommend_news': "Tin liên quan",
  'category': "Danh mục",
  'delete_items_warning': "Bạn có thực sự muốn xóa sản phẩm này khỏi giỏ hàng không?",
  'your_cat': "Giỏ hàng của bạn",
  'total': "Tổng cộng",
  'add_voucher_code': "Thêm mã giảm giá",
  'checkout': "Mua",
  'address': "Địa chỉ",
  'add_new_address': "Thêm địa chỉ mới",
  'pick_location': "Lựa chọn khu vực",
  'delivery': "Vận chuyển",
  'estimated': "Thời hạn",
  'place_order': "Đặt hàng",
  'price_detail': "Chi tiết",
};
