const Map<String, String> EN = {
  //login
  'description_logo': 'Free posting - Search as desired',
  'user_email_phone_field': 'Username, phone number or email',
  "password_field": 'Password',
  "login": 'Login',
  "forgot_password": 'Forgot password',
  "go_register": 'Do not have an account? Create Account',
  'or_sign_in_with': 'Or sign in with',
  //register
  'username_field': 'Username',
  'name_field': 'Fullname',
  'email_field': 'Email',
  'phone_field': 'Phone',
  'repassword_field': 'Confirm Password',
  'register': 'Register',
  'go_login': 'Already have account? Login',
  //forgot pass
  //more
  'account_balance': 'Account balance',
  'normal': 'Normal',
  'admin': 'Administration',
  'update_info': 'Edit information',
  'change_password': 'Change password',
  'version': 'Version',
  'my_store': 'My store',
  'manage_posting': 'Manage posting',
  'store_management': 'Store management',
  'safe_purchase': 'Safe purchase',
  'help': 'Help',
  'about_tizi': 'About Tizi',
  'appearance': "Appearance",
  'language': 'Language',
  'log_out': 'Log out',
  'sign_in/sign_up': 'Sign in/ Sign up',
  //setting
  'setting': 'Setting',
  //common
  'home': 'Home',
  'saved_news': 'Saved News',
  'message': 'Message',
  'more': 'More',
  'error': 'An error has occurred',
  'skip': 'Skip',
  'back': 'Back',
  'vn_language': 'Vietnamese',
  'jp_language': "Japanese",
  'light_theme': "Light Theme",
  'dark_theme': "Dark Theme",
  'settings': "Settings",
  'select_language': "Select language",
  'input_code': "Input Code",
  'hint_search_text': "What are you looking for?",
  'history_search': "Recent",
  'result_search': "Result",
  'negotiate': "Negotiate",
  'detail_product': "Product detail",
  'view_more': "View more",
  'see_less': "See less",
  'view_shop': "View shop",
  'report': "Report",
  'personal': "Personal",
  'num_of_news': "News",
  'create_at': "Start date",
  'recommend_news': "Recommend",
  'category': "Category",
  'delete_items_warning': "Are you sure want to delete this item?",
  'your_cart': "Your cart",
  'total': "Total",
  'add_voucher_code': "Add voucher code",
  'checkout': "Checkout",
  'address': "Address",
  'add_new_address': "Add new address",
  'pick_location': "Select location",
  'delivery': "Delivery",
  'estimated': "Estimated",
  'place_order': "Place order",
  'price_detail': "Price Detail",
  'intro_text_cart':
      "Select on the promo section at the bottom of the page to see all offers and freeship",
  'buy_now': "Buy now",
  'nums_of_item': "Amount",
  'item_colors': "Color",
  'activities': "Activities",
  'notifications': "Notifications",
  'history': "Histories",
  'edit': "Edit",
  'thanks_for_purchase':
      "\n\nThank you for your purchase. Our company values each and every customer. We strive to provide state-of-the-art devices that respond to our clients’ individual needs. If you have any questions or feedback, please don’t hesitate to reach out.",
  'track_order': 'Track your order',
  'delivery_in': 'Delivery in',
  'hours': 'hours',
  'total_mrp': 'Total MRP',
  'discount': 'Discount',
  'order_total': 'Order total',
  'free': 'Free',
  'standard_delivery': 'Standard Delivery',
  'extra_delivery': 'Extra Delivery',
  'fast_delivery': 'Fast Delivery',
  'delivery_charge': 'Delivery Charges',
  'no_info': 'Please fill information',
  'delivery_to': 'Delivery to',
  'delivery_type': 'Select delivery type',
  'order_list': 'Order list',
  'oder_bill': 'Order bill',
  'description': 'Description',
  'ready_in_cart': 'Product is ready in your cart',
  'view_cart': 'View cart',
};
